version: '2'

services:
  db:
    image: postgres:alpine
    environment:
        POSTGRES_USER: "pptk"
        POSTGRES_PASSWORD: "pptkpptk"
        POSTGRES_DB: "pptk"
    volumes:
      - /var/lib/pptk/postgresql/data:/var/lib/postgresql/data
    restart: always
  pptk:
    build: ./
    environment:
      STATIC_ROOT: '/code/static/'
      MEDIA_ROOT: '/code/media/'
      ALLOWED_HOSTS: "*"
      SECRET_KEY: "6d2e445309c2b7b6b9020f09de850e194e54175d5978f39558d42ca8bf5992a150f33549bdb8e82341bfe4c774555f30d1a7'
      DATABASES: "{'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'NAME': 'pptk', 'USER': 'pptk', 'PASSWORD': 'pptkpptk', 'HOST': 'db', 'PORT': '',}}"
    command: bash -c "sleep 5 && cd /code/ && python3 manage.py makemigrations --merge && python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn pptk_slides.wsgi -b unix:/code/run/pptk.sock --workers 3"
    volumes:
      - ./:/code
    depends_on:
      - db
    restart: always
